# Generated by Django 6.0.2 on 2026-03-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MERCADO', 'Mercado'), ('BOTANICO', 'Jardin Botanico'), ('ACUATICO', 'Jardin Acuatico'), ('HORTALIZAS', 'Hortalizas')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion de lo que hay en esta area')),
                ('video_principal', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('foto_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='jardin.seccion')),
            ],
        ),
    ]
