# Generated by Django 6.0.2 on 2026-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotogaleria',
            options={'ordering': ['fecha_subida'], 'verbose_name': 'Foto de galería', 'verbose_name_plural': 'Fotos de galería'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterField(
            model_name='seccion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de lo que hay en esta área'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(choices=[('JARDIN_BOTANICO', 'Jardín Botánico'), ('MUSEO', 'Museo Viviente: Orquídeas'), ('ACUATICO', 'Jardín Acuático'), ('HORTALIZAS', 'Hortalizas'), ('INVERNADERO', 'Invernadero'), ('EPIFITARIO', 'Epifitario'), ('MERCADO', 'Mercado')], max_length=50, unique=True),
        ),
    ]
