# Generated by Django 6.0.2 on 2026-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0002_alter_fotogaleria_options_alter_seccion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AddField(
            model_name='seccion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Número para ordenar las secciones en la página principal'),
        ),
    ]
