# Generated by Django 6.0.2 on 2026-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0003_alter_seccion_options_seccion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(choices=[('MUSEO', 'Museo Viviente: Orquídeas'), ('ACUATICO', 'Jardín Acuático'), ('EPIFITARIO', 'Epifitario'), ('INVERNADEROS', 'Invernaderos'), ('HORTALIZAS', 'Hortalizas'), ('MERCADO', 'Mercado')], max_length=50, unique=True),
        ),
    ]
