# Generated by Django 6.0.2 on 2026-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0004_alter_seccion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='seccion',
            name='descripcion_corta',
            field=models.TextField(blank=True, help_text='Texto breve y amigable para mostrar en la tarjeta principal'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='descripcion_detallada',
            field=models.TextField(blank=True, help_text='Texto más completo e informativo para mostrar dentro de la galería'),
        ),
    ]
