# Generated by Django 6.0.2 on 2026-03-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0005_remove_seccion_descripcion_seccion_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='enlace_seccion_completa',
            field=models.URLField(blank=True, help_text='Enlace a la página completa de esta sección (base de datos o sistema detallado)'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='descripcion_detallada',
            field=models.TextField(blank=True, help_text='Texto más completo e informativo para mostrar dentro de la ficha'),
        ),
    ]
