# Generated by Django 6.0.2 on 2026-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0006_seccion_enlace_seccion_completa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='descripcion_corta_en',
            field=models.TextField(blank=True, help_text='Texto breve en inglés para mostrar en la tarjeta principal'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='descripcion_detallada_en',
            field=models.TextField(blank=True, help_text='Texto más completo en inglés para mostrar dentro de la ficha'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Nombre de la sección en inglés', max_length=100),
        ),
    ]
