services:
  teya-web:
    build: .
    container_name: teya-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    expose:
      - "8000"
    networks:
      - npm_proxy

networks:
  npm_proxy:
    external: true

    